### PR TITLE
Changed exec to get_results

### PR DESCRIPTION
**Pull request by papi-knomic**
Fixed this error
 Uncaught Error: Call to undefined method wpdb::exec()

### CODE REVIEW

**Comment by as247** [comment]
We don't have this error. $this->getPdo() should return As247\WpEloquent\Database\WpPdo and exec function there already

**Comment by as247** [comment]
Exec function defined here line131 https://github.com/as247/wp-eloquent/blob/master/src/Database/WpPdo.php#L131

**Comment by papi-knomic** [comment]
error


This is the error I get when I leave it just as it is

**Comment by as247** [comment]
> error
> 
> This is the error I get when I leave it just as it is

could you try dump $this->getPdo() in line 112 to see which object returned

**Comment by papi-knomic** [comment]
full
This was returned
I get the wpdb object

**Comment by as247** [comment]
Hmm which version are you using?

**Comment by papi-knomic** [comment]
The latest version, but I'm starting to suspect it might not be the package but my PC, now I'm having an error in creating

"Call to undefined method wpdb::lastInsertId()"

I can see the data in the DB but I get this

**Comment by as247** [comment]
> The latest version, but I'm starting to suspect it might not be the package but my PC, now I'm having an error in creating
> 
> "Call to undefined method wpdb::lastInsertId()"
> 
> I can see the data in the DB but I get this

I'm not able to reproduce, please reach me on email as247@vui360.com to discuss more about the issue

**Pull request closed without merging**
